DigitalHeaven/src/java/webshop/beans/PurchaseManagedBean.java
package webshop.beans;

import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import webshop.beans.model.ShoppingCartItem;
import webshop.business.PurchaseBeanLocal;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@ManagedBean(name = "purchaseMB", eager = true)
@ViewScoped
public class PurchaseManagedBean {

    @ManagedProperty(value = "#{loginMB}")
    private LoginManagedBean loginBean;

    @ManagedProperty(value = "#{cart}")
    private ShoppingCartManagedBean korpaBean;

    @ManagedProperty(value = "#{sendMail}")
    private EmailManagedBean emailBean;

    @EJB
    private PurchaseBeanLocal purchaseBean;

    private String creditCard;

    public String submitPurchase() {

        if (purchaseBean.addPurchase(loginBean.getLoggedInUser(), korpaBean.getCartItems(), creditCard)) {
            emailBean.sendEmail(getProductList());
            korpaBean.emptyCart();
            return "success";
        }

        return "failure";
    }

    public String getProductList() {
        String result = "";
        List<ShoppingCartItem> items = korpaBean.getCartItems();
        for (ShoppingCartItem item : items) {
            result += (item.getProductNum()) + "x";
            result += (item.getProductName());
            result += ",\n\r";
        }
        return result;
    }

    public String getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(String creditCard) {
        this.creditCard = creditCard;
    }

    public LoginManagedBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(LoginManagedBean loginBean) {
        this.loginBean = loginBean;
    }

    public ShoppingCartManagedBean getKorpaBean() {
        return korpaBean;
    }

    public void setKorpaBean(ShoppingCartManagedBean korpaBean) {
        this.korpaBean = korpaBean;
    }

    public EmailManagedBean getEmailBean() {
        return emailBean;
    }

    public void setEmailBean(EmailManagedBean emailBean) {
        this.emailBean = emailBean;
    }

}

DigitalHeaven/src/java/webshop/beans/ShoppingCartManagedBean.java
package webshop.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import webshop.beans.model.ShoppingCartItem;
import webshop.business.model.Proizvod;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@Named("cart")
@SessionScoped
public class ShoppingCartManagedBean implements Serializable {

    private List<ShoppingCartItem> cartItems = new ArrayList<>();

    private int productNum;

    public void addProduct(Proizvod proizvod) {
        for (ShoppingCartItem sci : cartItems) {
            if (sci.getProductName().equals(proizvod.getNaziv())) {
                sci.setProductNum(sci.getProductNum() + productNum);
                return;
            }
        }
        ShoppingCartItem newItem = new ShoppingCartItem();
        newItem.setProduct(proizvod);
        newItem.setProductNum(productNum);
        cartItems.add(newItem);
    }

    public int getTotalPrice() {
        int total = 0;
        for (ShoppingCartItem item : cartItems) {
            total += item.getTotalPrice();
        }
        return total;
    }

    public void emptyCart() {
        cartItems = new ArrayList<>();
    }

    public List<ShoppingCartItem> getCartItems() {
        return cartItems;
    }

    public int getProductNum() {
        return productNum;
    }

    public void setProductNum(int productNum) {
        this.productNum = productNum;
    }

}

DigitalHeaven/src/java/webshop/business/PurchaseBean.java
package webshop.business;

import java.util.ArrayList;
import java.util.List;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import webshop.beans.model.ShoppingCartItem;
import webshop.business.model.Korisnik;
import webshop.business.model.Kupovina;
import webshop.business.model.KupovinaProizvodi;
import webshop.constants.Constants;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@Stateless
public class PurchaseBean implements PurchaseBeanLocal {

    @PersistenceContext(unitName = Constants.PERSISTENCE_UNIT_NAME)
    private EntityManager em;

    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    @Override
    public boolean addPurchase(Korisnik korisnik, List<ShoppingCartItem> cartItems, final String brojKartice) {
        if (korisnik == null || cartItems == null || cartItems.size() == 0) {
            return false;
        }

        Kupovina kupovina = new Kupovina();
        kupovina.setBrojKartice(brojKartice);
        kupovina.setIme(korisnik.getIme());
        kupovina.setPrezime(korisnik.getPrezime());
        kupovina.setIdKorisnik(korisnik);
        kupovina.setTelefon(korisnik.getTelefon());

        List<KupovinaProizvodi> kpList = new ArrayList<KupovinaProizvodi>();
        int totalPrice = 0;
        for (ShoppingCartItem item : cartItems) {
            KupovinaProizvodi kp = new KupovinaProizvodi();
            kp.setProizvodId(item.getProduct());
            kp.setKolicina(item.getProductNum());
            kp.setKupovinaId(kupovina);
            totalPrice += (item.getProductNum() * item.getProduct().getCena());
            kpList.add(kp);
        }

        kupovina.setKupovinaProizvodiList(kpList);
        kupovina.setCena(totalPrice);

        try {
            em.persist(kupovina);
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

    }

}

DigitalHeaven/web/secured/purchase.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Potvrda kupovine</title>
        <link href="../resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <h2>Web Shop - Potvrda kupovine</h2>
            <hr />
            <h:form>
                <h:panelGrid columns="2" cellpadding = "10" cellspacing = "1">

                    <h:outputText value="Ime:" />
                    <h:outputText value="#{purchaseMB.loginBean.loggedInUser.ime}" />

                    <h:outputText value="Prezime:" />
                    <h:outputText value="#{purchaseMB.loginBean.loggedInUser.prezime}" />

                    <h:outputText value="Broj kartice:" />
                    <h:inputText required="true" value="#{purchaseMB.creditCard}" requiredMessage="Polje broj kartice je obavezno." > 
                        <f:validator validatorId="CreditCardValidator"/>
                    </h:inputText>

                    <h:outputText value="Proizvodi:" />
                    <h:outputText value="#{purchaseMB.productList}" />

                    <h:outputText value="Ukupna cena: " />
                    <h:outputText value="#{purchaseMB.korpaBean.totalPrice}" />

                    <h:commandButton value="Potvrda" action="#{purchaseMB.submitPurchase}" />
                </h:panelGrid>
                <h:messages />
            </h:form>
            <h:outputLink value="../index.xhtml">Povratak na kupovinu</h:outputLink>
        </div>
    </h:body>
</html>