DigitalHeaven/src/java/webshop/beans/LoginManagedBean.java
package webshop.beans;

import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import webshop.business.LoginBeanLocal;
import webshop.business.model.Korisnik;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@ManagedBean(name = "loginMB", eager = true)
@SessionScoped
public class LoginManagedBean implements Serializable {

    private String username;
    private String password;

    private String message = "";

    private Korisnik loggedInUser = null;

    @EJB
    private LoginBeanLocal loginBean;

    public String login() {

        if (loggedInUser != null) {
            return "success";
        }

        Korisnik korisnik = loginBean.login(username, password);

        if (korisnik == null) {
            message = "Neispravna kombinacija korisničkog imena i lozinke.";
            return "failure";
        }

        this.loggedInUser = korisnik;

        return "success";
    }

    public void logout() {
        loggedInUser = null;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Korisnik getLoggedInUser() {
        return loggedInUser;
    }

    public void setLoggedInUser(Korisnik loggedInUser) {
        this.loggedInUser = loggedInUser;
    }
    
    public boolean isLoggedIn() {
        return (loggedInUser != null);
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}

DigitalHeaven/src/java/webshop/beans/ShoppingCartManagedBean.java
package webshop.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import webshop.beans.model.ShoppingCartItem;
import webshop.business.model.Proizvod;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@Named("cart")
@SessionScoped
public class ShoppingCartManagedBean implements Serializable {

    private List<ShoppingCartItem> cartItems = new ArrayList<>();

    private int productNum;

    public void addProduct(Proizvod proizvod) {
        for (ShoppingCartItem sci : cartItems) {
            if (sci.getProductName().equals(proizvod.getNaziv())) {
                sci.setProductNum(sci.getProductNum() + productNum);
                return;
            }
        }
        ShoppingCartItem newItem = new ShoppingCartItem();
        newItem.setProduct(proizvod);
        newItem.setProductNum(productNum);
        cartItems.add(newItem);
    }

    public int getTotalPrice() {
        int total = 0;
        for (ShoppingCartItem item : cartItems) {
            total += item.getTotalPrice();
        }
        return total;
    }

    public void emptyCart() {
        cartItems = new ArrayList<>();
    }

    public List<ShoppingCartItem> getCartItems() {
        return cartItems;
    }

    public int getProductNum() {
        return productNum;
    }

    public void setProductNum(int productNum) {
        this.productNum = productNum;
    }

}

DigitalHeaven/src/java/webshop/beans/model/ShoppingCartItem.java
package webshop.beans.model;

import java.io.Serializable;
import webshop.business.model.Proizvod;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
public class ShoppingCartItem implements Serializable {

    private Proizvod product;
    private int productNum;

    public String getProductName() {
        if (product == null) {
            return null;
        }
        return product.getNaziv();
    }

    public int getProductNum() {
        return productNum;
    }

    public void setProductNum(int productNum) {
        this.productNum = productNum;
    }

    public int getPrice() {
        if (product == null) {
            return 0;
        }
        return product.getCena();
    }

    public int getTotalPrice() {
        return product.getCena() * productNum;
    }

    public void setProduct(Proizvod product) {
        this.product = product;
    }

    public Proizvod getProduct() {
        return product;
    }

}

DigitalHeaven/src/java/webshop/business/LoginBean.java
package webshop.business;

import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import webshop.business.model.Korisnik;
import webshop.constants.Constants;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@Stateless
public class LoginBean implements LoginBeanLocal {

    @PersistenceContext(unitName = Constants.PERSISTENCE_UNIT_NAME)
    private EntityManager em;

    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    @Override
    public Korisnik login(String username, String password) {

        try {
            Query query = em.createNamedQuery("Korisnik.findByKorisnickoImeLozinka");
            query.setParameter("korisnickoIme", username);
            query.setParameter("lozinka", password);

            Korisnik result = (Korisnik) query.getSingleResult();

            return result;
        } catch (NoResultException nre) {
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

    }

}

DigitalHeaven/src/java/webshop/business/RegisterBean.java
package webshop.business;

import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import webshop.business.model.Korisnik;
import webshop.constants.Constants;

/**
 *
 * @author Igor Strbac <mail@igorstrbac.com>
 */
@Stateless
public class RegisterBean implements RegisterBeanLocal {

    @PersistenceContext(unitName = Constants.PERSISTENCE_UNIT_NAME)
    private EntityManager em;

    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    @Override
    public boolean register(String username, String password, String name, String surname, String email, String phoneNumber) {

        try {
            Query query = em.createNamedQuery("Korisnik.findByKorisnickoIme");
            query.setParameter("korisnickoIme", username);

            Korisnik k = (Korisnik) query.getSingleResult();

            if (k != null) {
                return false;
            }

        } catch (NoResultException nre) {
            
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

        try {
            Korisnik noviKorisnik = new Korisnik();
            noviKorisnik.setKorisnickoIme(username);
            noviKorisnik.setLozinka(password);
            noviKorisnik.setIme(name);
            noviKorisnik.setPrezime(surname);
            noviKorisnik.setEmail(email);
            noviKorisnik.setTelefon(phoneNumber);

            em.persist(noviKorisnik);

            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

    }

}

DigitalHeaven/web/aboutus.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>AboutUs</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i|Orbitron:400,700&amp;subset=latin-ext" rel="stylesheet"/>  
        <link href="resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <div id="main">
                <h2>O nama:</h2>
            </div><!-- end #main -->
            <h:outputLink value="../index.xhtml">Povratak na glavnu stranu</h:outputLink>
        </div><!-- end #wrapper -->
    </h:body>
</html>

DigitalHeaven/web/contact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i|Orbitron:400,700&amp;subset=latin-ext" rel="stylesheet"/>  
        <link href="resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <div id="main">
                <h2>Kontakt mail:</h2>
                <h4>prodaja@digitalheaven.co</h4>
                <h:outputLink value="../index.xhtml">Povratak na glavnu stranu</h:outputLink>
            </div><!-- end #main -->
        </div><!-- end #wrapper -->

    </h:body>
</html>

DigitalHeaven/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>DigitalHeaven WebShop - Dobro došli</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i|Orbitron:400,700&amp;subset=latin-ext" rel="stylesheet"/>  
        <link href="resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <div id="header">

                <div id="logo">
                    <p><b>DigitalHeaven.co</b></p>
                </div>

                <div id="slogan">
                    <p>Vaš digitalni raj</p>
                </div>

            </div><!-- end #header -->

            <div id="nav">

                <ul>
                    <li><a href="index.xhtml">Naslovna strana</a></li>
                    <li><a href="aboutus.xhtml">O nama</a></li>
                    <li><a href="contact.xhtml">Kontakt</a></li>
                </ul>

            </div><!-- end #nav -->

            <div id="main">
                <div id="login">
                    <h:form rendered="#{loginMB.loggedIn}">
                        <h:panelGrid id="userPanelId">
                            <p>Prijavljeni korisnik: #{loginMB.loggedInUser.ime} #{loginMB.loggedInUser.prezime} <h:commandLink value="Odjava" actionListener="#{loginMB.logout()}" /></p>
                        </h:panelGrid>
                    </h:form>
                    <h:panelGrid rendered="#{not loginMB.loggedIn}">
                        <p>Za prijavu na Web Shop kliknite na <h:outputLink value="login.xhtml">prijava</h:outputLink></p>
                        <p>Vi ste nov korisnik? Registrujte se klikom na link <h:outputLink value="register.xhtml">registracija</h:outputLink></p>
                    </h:panelGrid>
                </div> <!-- end #login -->
                <hr />
                <h2>Dobro došli na DigitalHeaven Webshop</h2>
                <hr />
                <h:form id="productForm">
                    <h:dataTable value = "#{products.products}" var = "pr">

                        <h:column>    				
                            <f:facet name = "header">Naziv</f:facet>    				
                                #{pr.naziv}
                        </h:column>

                        <h:column>
                            <f:facet name = "header">Cena (din.)</f:facet>
                                #{pr.cena}
                        </h:column>

                        <h:column>
                            <f:facet name = "header"></f:facet>
                            <h:commandButton value="Dodaj">
                                <f:ajax execute="@form" render="korpaid" listener="#{cart.addProduct(pr)}" />
                            </h:commandButton>
                        </h:column>
                    </h:dataTable>
                    <br />
                    <h:outputText value="Izaberite željenu količinu: " />
                    <h:selectOneMenu value = "#{cart.productNum}"> 
                        <f:selectItem itemValue = "1" itemLabel = "1" /> 
                        <f:selectItem itemValue = "2" itemLabel = "2" /> 
                        <f:selectItem itemValue = "3" itemLabel = "3" /> 
                        <f:selectItem itemValue = "4" itemLabel = "4" /> 
                        <f:selectItem itemValue = "5" itemLabel = "5" /> 
                    </h:selectOneMenu> 
                </h:form>
                <br />
                <h4>Vaša korpa:</h4>
                <hr />
                <h:dataTable id="korpaid" value = "#{cart.cartItems}" var = "item">

                    <h:column>    				
                        <f:facet name = "header">Naziv</f:facet>    				
                            #{item.productName}
                    </h:column>

                    <h:column>
                        <f:facet name = "header">Cena (din.)</f:facet>
                            #{item.price}
                    </h:column>

                    <h:column>
                        <f:facet name = "header">Količina</f:facet>
                            #{item.productNum}
                    </h:column>

                    <h:column>
                        <f:facet name = "header"><b>Ukupna cena</b></f:facet>
                        <b>#{item.totalPrice}</b>
                    </h:column>

                </h:dataTable>

                <hr />

                <h:outputLink value="secured/purchase.xhtml">Potvrda kupovine</h:outputLink>
            </div><!-- end #main -->
            <div id="footer">
                <p>Copyright &copy; DigitalHeaven.co 2018</p>
            </div><!-- end #footer -->
        </div><!-- end #wrapper -->
    </h:body>



</html>

DigitalHeaven/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Prijava na Webshop</title>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <link href="resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <h2>Prijava   na   DigitalHeaven   Webshop</h2>
            <hr />
            <div id="mainlogin"> 
                <h:form>
                    <h:panelGrid id = "panel" columns = "3"
                                 cellpadding = "10" cellspacing = "1">

                        <h:outputLabel value = "Molimo  unesite  Vaše korisničko ime:" />
                        <h:inputText id="unfld" required="true" requiredMessage="Morate uneti korisničko ime" value="#{loginMB.username}" />
                        <h:message for="unfld" style ="color:red" />

                        <h:outputLabel value = "Molimo unesite lozinku:" />
                        <h:inputSecret id="passfld" required="true" requiredMessage="Morate uneti lozinku" value="#{loginMB.password}" />
                        <h:message for="passfld" style ="color:red" />
                        <div class="g-recaptcha" data-sitekey="6LcTXoQUAAAAAE7ayUw43KlB6dDfTo1WtEDn2k9I"></div>
                        <div id="footerlogin">
                            <f:facet name = "footer">
                                <h:panelGroup style = "display:block; text-align:left">
                                    <h:commandButton id = "submit" value = "Potvrda" action="#{loginMB.login()}" />
                                </h:panelGroup>
                            </f:facet>
                        </div><!-- end #footerlogin -->
                    </h:panelGrid>

                    <h3><h:outputLabel value="#{loginMB.message}" /></h3>
                </h:form>

                <h:outputLink value="index.xhtml">Povratak na glavnu stranu</h:outputLink>
            </div><!-- end #mainLogin -->
        </div><!-- end #wrapper -->
    </h:body>

</html>

DigitalHeaven/web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Registracija</title>
        <link href="resources/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div id="wrapper">
            <h2>Registracija novih korisnika</h2>
            <hr />

            <h:form>
                <h:panelGrid id = "panel" columns = "4"
                             cellpadding = "10" cellspacing = "1">
                    <h:outputLabel value = "Korisničko ime:" />
                    <h:inputText id="unfld" required="true" requiredMessage="Polje korisničko ime je obavezno" value="#{register.username}" />
                    <h:outputLabel value = "" />
                    <h:message for="unfld" />

                    <h:outputLabel value = "Lozinka:" />
                    <h:inputSecret id="passfld" required="true" requiredMessage="Polje lozinka je obavezno" value="#{register.password}" validatorMessage="Neispravan format,pratite uputstvo" >
                        <f:validateRegex pattern="((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,20})" />
                    </h:inputSecret>
                    <h:outputLabel value = "6 do 20 karaktera sa najmanje jednom cifrom,
                                   jednim velikim i jednim malim slovom" />
                    <h:message for="passfld" />

                    <h:outputLabel value = "Ime:" />
                    <h:inputText id="namfld" required="true" requiredMessage="Polje ime je obavezno" value="#{register.name}" />
                    <h:outputLabel value = "" />
                    <h:message for="namfld" />


                    <h:outputLabel value = "Prezime:" />
                    <h:inputText id="surfld" required="true" requiredMessage="Polje prezime je obavezno" value="#{register.surname}" />
                    <h:outputLabel value = "" />
                    <h:message for="surfld" />

                    <h:outputLabel value = "E-mail:" />
                    <h:inputText id="emailfld" required="true" requiredMessage="Polje eMail je obavezno" value="#{register.email}" validatorMessage="Email nije ispravan!">
                        <f:validateRegex pattern="^[_\w-\+]+(\.[_\w-]+)*@[\w-]+(\.[\w]+)*(\.[A-Za-z]{2,})$"></f:validateRegex>
                    </h:inputText>
                    <h:outputLabel value = "" />                
                    <h:message for="emailfld" />

                    <h:outputLabel value = "Kontakt telefon:" />
                    <h:inputText id="phonefld" required="true" requiredMessage="Polje telefon je obavezno" value="#{register.phoneNumber}" />
                    <h:outputLabel value = "" />                
                    <h:message for="phonefld" /> 

                    <f:facet name = "footer">
                        <h:panelGroup style = "display:block; text-align:left">
                            <h:commandButton id = "submit" value = "Potvrda" action="#{register.register()}" />
                        </h:panelGroup>
                    </f:facet>
                </h:panelGrid>
                <h3><h:outputLabel value="#{register.message}" /></h3>
            </h:form>
            <h:outputLink value="index.xhtml">Povratak na glavnu stranu</h:outputLink>
        </div><!-- end #wrapper -->
    </h:body>
</html>